### ISSUE TITLE
fast_stack not compiling

### ISSUE THREAD

**Issue by andywenk** [SamSaffron/flamegraph#15]
Hi,

first of all thanks for this gem. I tried to include it together with mini-profiler. This is a 
- MAC OS X 10.11
- Rails 4.2.4
- Ruby 2.2.3
- bundler 1.10.6
- rubygems 2.4.5.1

setup. I get the following error when trying to run `bundle` and also when trying to install `fast_stack` standalone via `gem install flamegraph`:

```
Building native extensions.  This could take a while...
ERROR:  Error installing fast_stack:
    ERROR: Failed to build gem native extension.

    /Users/andwen/.rbenv/versions/2.2.3/bin/ruby -r ./siteconf20151009-33231-16ysef.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling fast_stack.c
linking shared-object fast_stack/fast_stack.bundle
ld: library not found for -lgmp
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [fast_stack.bundle] Error 1

make failed, exit code 2
```

Is this a compiler issue? I have `Apple LLVM version 7.0.0 (clang-700.0.72)` installed (gcc -v)

Thanks for any help.

Cheers

Andy

**Comment by SamSaffron** [comment]
we need to clarify in the docs but in 2.1 and above you should use
stackprof

https://github.com/SamSaffron/flamegraph/blob/master/lib/flamegraph.rb#L5

can you update the readme so others do not get stuck?

**Comment by edbond** [comment]
Note added to readme, can be closed now I think.
