### ISSUE TITLE
Application with flamegraph installed fails to load (missing deps)

### ISSUE THREAD

**Issue by pik** [SamSaffron/flamegraph#19]
So `flamegraph` will attempt to require either `stackprof` or `fast_stack`

```ruby
if RUBY_VERSION >= "2.1.0".freeze
  begin
    require "stackprof"
  rescue LoadError
    STDERR.puts "Please require the stackprof gem falling back to fast_stack"
    require "fast_stack"
  end
```

When the later fails Rails Server / Console will fail to initialize and exit. Should one of these be added to the dependency list, or otherwise the a rescue added for `require "fast_stack"`  ?

**Comment by SamSaffron** [comment]
I am not sure what we can do here, without both of these gem flamegraph is broken, why include it?

**Comment by pik** [comment]
Would something like this do it? `spec.add_dependency( RUBY_VERSION >= "2.1.0".freeze ? "stackprof" : "fast_stack" )`

**Comment by SamSaffron** [comment]
nope, fast_stack still works on 2.1.0 its just that stackprof is preferred cause it uses the new profiling apis

**Comment by josh-lendeavor** [comment]
I started getting this error when I moved to Ruby `2.3.1` I'm not sure if it's the Ruby upgrade of the Bundler upgrade to `1.12.5`, but my application is unable to find either `stackprof` or `fast_stack`.

**Comment by SamSaffron** [comment]
wait, did you add either of those gems to your bundle?

**Comment by josh-lendeavor** [comment]
Yea, it turns out my problem was neither of those gems was added to the bundle. It worked before with them being installed on the system, and not being in the bundle. Now they are required to be part of the bundle. So, I'm not sure if any action is required here.

Although, if one of them was required by default then this gem would work out of the box. We wouldn't need to find and be declaring dependencies of gems in our `Gemfile`.

**Comment by nickrivadeneira** [comment]
@SamSaffron Is adding either `stackprof` or `fast_stack` to the Gemfile a requirement for installation? Nothing is mentioned of this in the README, but my impression is that it is required. If so, I'd be happy to open a PR to add it to the README.

**Comment by SamSaffron** [comment]
Yes either are required, I think fairly soon we can drop support for 2.0
and make stackprof a strong requirement.
