### ISSUE TITLE
Faster loading and zoom

### ISSUE THREAD

**Issue by thisduck** [SamSaffron/flamegraph#23]
Hi @SamSaffron 

I've made a few changes (demo in video link: https://drive.google.com/open?id=0B-8YziZr08bQaEF3VmNIQURFMWM ):

1. Added the ability to color by gem or method via radio buttons, without having to refresh the page.
2. Filter by width of frame (to get quick visibility on slower calls).
3. Ability to see callee in addition of the backtrace in the modal.
4. Zoom via click, instead of having to click and drag.

Would love your thoughts.

Additionally I'm working on getting filtering via method/gem, as well.

**Comment by SamSaffron** [comment]
thanks for this! I like the changes but the UI needs to be a bit more
polished, maybe have it default off for now just to get it merged in and
then we can polish up the UI a bit.

**Comment by thisduck** [comment]
Yup! I will polish things up more and open a pull request soon! Just wanted to run it by you first.

I got filtering via gem working as well.

**Comment by thisduck** [comment]
@SamSaffron Are you okay with adding bootstrap or some other css/js library to do things like tooltips and nicer looking UI?
