### ISSUE TITLE
stackprof dependency required for ruby 2.1

### ISSUE THREAD

**Issue by chuckbjones** [SamSaffron/flamegraph#4]
I don't know anything about gemspecs, but I assume that since stackprof is only needed for ruby 2.1 that you can't add it as a dependency? If so, this should probably be documented in the README. 

For others having this problem:
`LoadError: cannot load such file -- stackprof`,
add `gem 'stackprof', '~> 0.2.7'` to your Gemfile.

**Comment by crivotz** [comment]
Just for info you also receive the message "*Please require the stackprof gem falling back to fast_stack*" if you do *rake log:clear* or *rake tmp:clear*

**Comment by marcamillion** [comment]
I am getting that same `Please require the stackprof gem falling back to fast_stack` error message when I do `rake db:migrate`. 

But the weird thing is it only happens on 1 branch, not both branches.

**Comment by SamSaffron** [comment]
flamegraph without stackprof on 2.1 is an inferior experience, why are you
not including it ?
