### ISSUE TITLE
Request: ESC to close Frame Info

### ISSUE THREAD

**Issue by mahemoff** [SamSaffron/flamegraph#8]
Nice tool here. Can you please make it possible to close with a keyboard shortcut as moving the mouse outside the window can make it difficult to jump around and drill into different sections.

**Comment by SamSaffron** [comment]
Sure, can you submit a PR ?

**Comment by agrimm** [comment]
Should this ticket be closed now?

**Comment by SamSaffron** [comment]
yeah ... oops !
